name = "telegram-exchange-bot"
main = "src/index.js"
compatibility_date = "2024-03-25"

[[d1_databases]]
binding = "DB" 
database_name = "LinksDB"
database_id = "هنا_تضع_الكود_الذي_نسخته" # الصق الـ ID هنا
